name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
      prerelease:
        description: 'Mark as a pre-release'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: pyinstaller --noconfirm --onefile --windowed --name "flashforge-emulator" main.py

    - name: Package executable
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          echo "Windows executable does not need packaging."
        elif [ "${{ runner.os }}" == "macOS" ]; then
          zip -j dist/flashforge-emulator-macos.zip dist/flashforge-emulator
        else
          zip -j dist/flashforge-emulator-linux.zip dist/flashforge-emulator
        fi

    - name: Upload Windows Artifact
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: executables-${{ runner.os }}
        path: dist/flashforge-emulator.exe

    - name: Upload Linux/macOS Artifact
      if: runner.os != 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: executables-${{ runner.os }}
        path: dist/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create releases

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: executables
        pattern: executables-*
        merge-multiple: true

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        prerelease: ${{ github.event.inputs.prerelease }}
        files: executables/*
