name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
      prerelease:
        description: 'Mark as a pre-release'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: pyinstaller --noconfirm --onefile --windowed --name "flashforge-emulator" main.py

    - name: Rename executable (Linux)
      if: runner.os == 'Linux'
      run: mv dist/flashforge-emulator dist/flashforge-emulator-linux

    - name: Rename executable (macOS)
      if: runner.os == 'macOS'
      run: mv dist/flashforge-emulator dist/flashforge-emulator-macos

    - name: Rename executable (Windows)
      if: runner.os == 'Windows'
      run: mv dist/flashforge-emulator.exe dist/flashforge-emulator-windows.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: executables-${{ runner.os }}
        path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create releases

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: executables
        pattern: executables-*
        merge-multiple: true

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        prerelease: ${{ github.event.inputs.prerelease }}
        files: executables/*
